# Generated by Django 6.0.4 on 2026-04-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.CharField(default='/burger.jpg', max_length=200),
        ),
    ]
